
// https://login.wrike.com/oauth2/authorize/v4?client_id=kFNXLYkx&response_type=code

// http://localhost/?code=l0AeYhiJfRssM8yMzIBFJZtynczf40FeERpc1lyjjz0cziMNmQPL93cjboa8EFeP-N

// curl -X POST -d "client_id=kFNXLYkx&client_secret=XUJvwgX1oUGcYMZeENoLE4AdygXyK5gP7U6SQo1FTcXnIYzUYwsugv9wJJJ7YMBL&grant_type=authorization_code&code=mKrBugEhJR44GpcyRkIAmgvkIJC6aXDrYMxMvK8Evqmgsft8uEGE1HhubjqoAGXf-N" https://login.wrike.com/oauth2/token

// curl -X GET https://www.wrike.com/api/v4/contacts?me=true&access_token=eyJ0dCI6InAiLCJhbGciOiJIUzI1NiIsInR2IjoiMSJ9.eyJkIjoie1wiYVwiOjE4MjY0MTgsXCJpXCI6NzIwMDQyNixcImNcIjo0NjIxMTg4LFwidVwiOjM1NzA1OTMsXCJyXCI6XCJVU1wiLFwic1wiOltcIldcIixcIkZcIixcIklcIixcIlVcIixcIktcIixcIkNcIixcIkRcIixcIk1cIixcIkFcIixcIkxcIixcIlBcIl0sXCJ6XCI6W10sXCJ0XCI6MH0iLCJpYXQiOjE1OTg0OTE0NTR9.v__LQfGSXS6JGbPSHcBLhIps68B-8nUgD0Wo62UbWH4


// { "access_token": "eyJ0dCI6InAiLCJhbGciOiJIUzI1NiIsInR2IjoiMSJ9.eyJkIjoie1wiYVwiOjE4MjY0MTgsXCJpXCI6NzIwMDQ0MSxcImNcIjo0NjIxMTg4LFwidlwiOlwiXCIsXCJ1XCI6MzU3MDU5MyxcInJcIjpcIlVTXCIsXCJzXCI6W1wiTlwiXSxcInpcIjpbXSxcInRcIjoxNTk4NDk2Nzk1MDAwfSIsImV4cCI6MTU5ODQ5Njc5NSwiaWF0IjoxNTk4NDkzMTk1fQ.FXc16JCPgRNWeBnWVzmptU029u4O8LQTrS3Tu3yyAHM", "token_type": "bearer", "host": "www.wrike.com", "expires_in": 3600, "refresh_token": "eyJ0dCI6InAiLCJhbGciOiJIUzI1NiIsInR2IjoiMSJ9.eyJkIjoie1wiYVwiOjE4MjY0MTgsXCJpXCI6NzIwMDQ0MSxcImNcIjo0NjIxMTg4LFwidlwiOlwiXCIsXCJ1XCI6MzU3MDU5MyxcInJcIjpcIlVTXCIsXCJzXCI6W1wiTlwiXSxcInpcIjpbXCJyc2hcIl0sXCJ0XCI6MTU5ODQ5Njc5NTAwMH0iLCJleHAiOjE1OTg0OTY3OTUsImlhdCI6MTU5ODQ5MzE5NX0.ueCwqatkxxtoqL0Xdydy71Od7H9t90MXUF3gtNmIx_Q"  }